import { getMenuImageChoice } from "./menu-images";
import type { MenuItem, MenuMasterState, RestaurantTable } from "./types";

export const DEMO_STATE_VERSION = 3;
export const DEMO_TABLE_TOKEN = "table-7-demo";

const tables: RestaurantTable[] = Array.from({ length: 12 }, (_, index) => {
  const tableNumber = index + 1;
  return {
    id: `table-${tableNumber}`,
    restaurantId: "restaurant-demo",
    name: `Table ${tableNumber}`,
    token: `table-${tableNumber}-demo`,
  };
});

const menuItems: MenuItem[] = [
  {
    id: "item-satay",
    restaurantId: "restaurant-demo",
    categoryId: "cat-starters",
    name: "Buffalo Wings",
    description: "Crispy wings tossed in buffalo sauce with ranch dip.",
    priceCents: 890,
    imageUrl: getMenuImageChoice("satay").url,
    isAvailable: true,
    sortOrder: 1,
    options: [
      {
        id: "opt-satay-extra",
        menuItemId: "item-satay",
        name: "Extra ranch",
        priceDeltaCents: 120,
      },
    ],
  },
  {
    id: "item-papaya-salad",
    restaurantId: "restaurant-demo",
    categoryId: "cat-starters",
    name: "Loaded Nachos",
    description: "Tortilla chips, cheddar, salsa, jalapenos, sour cream, and guacamole.",
    priceCents: 760,
    imageUrl: getMenuImageChoice("salad").url,
    isAvailable: true,
    sortOrder: 2,
    options: [
      {
        id: "opt-salad-mild",
        menuItemId: "item-papaya-salad",
        name: "No jalapenos",
        priceDeltaCents: 0,
      },
      {
        id: "opt-salad-extra-spicy",
        menuItemId: "item-papaya-salad",
        name: "Extra jalapenos",
        priceDeltaCents: 0,
      },
    ],
  },
  {
    id: "item-tom-yum",
    restaurantId: "restaurant-demo",
    categoryId: "cat-starters",
    name: "Mozzarella Sticks",
    description: "Golden mozzarella sticks with warm marinara sauce.",
    priceCents: 780,
    imageUrl: getMenuImageChoice("soup").url,
    isAvailable: true,
    sortOrder: 3,
    options: [
      {
        id: "opt-tom-yum-creamy",
        menuItemId: "item-tom-yum",
        name: "Extra marinara",
        priceDeltaCents: 80,
      },
    ],
  },
  {
    id: "item-pad-thai",
    restaurantId: "restaurant-demo",
    categoryId: "cat-mains",
    name: "House Burger",
    description: "Beef patty, cheddar, pickles, lettuce, tomato, and pub sauce.",
    priceCents: 1290,
    imageUrl: getMenuImageChoice("noodles").url,
    isAvailable: true,
    sortOrder: 1,
    options: [
      {
        id: "opt-pad-spicy",
        menuItemId: "item-pad-thai",
        name: "Add bacon",
        priceDeltaCents: 180,
      },
      {
        id: "opt-burger-double",
        menuItemId: "item-pad-thai",
        name: "Double patty",
        priceDeltaCents: 350,
      },
    ],
  },
  {
    id: "item-curry",
    restaurantId: "restaurant-demo",
    categoryId: "cat-mains",
    name: "Loaded Fries",
    description: "Fries with cheese sauce, bacon, scallions, and sour cream.",
    priceCents: 990,
    imageUrl: getMenuImageChoice("curry").url,
    isAvailable: false,
    sortOrder: 2,
    options: [
      {
        id: "opt-curry-rice",
        menuItemId: "item-curry",
        name: "Extra bacon",
        priceDeltaCents: 180,
      },
    ],
  },
  {
    id: "item-crispy-pork",
    restaurantId: "restaurant-demo",
    categoryId: "cat-mains",
    name: "Fish and Chips",
    description: "Beer-battered fish with fries, tartar sauce, and lemon.",
    priceCents: 1350,
    imageUrl: getMenuImageChoice("rice-bowl").url,
    isAvailable: true,
    sortOrder: 3,
    options: [
      {
        id: "opt-pork-egg",
        menuItemId: "item-crispy-pork",
        name: "Extra tartar",
        priceDeltaCents: 90,
      },
    ],
  },
  {
    id: "item-grilled-salmon",
    restaurantId: "restaurant-demo",
    categoryId: "cat-mains",
    name: "Grilled Salmon",
    description: "Charred salmon with herb potatoes, greens, and lemon butter.",
    priceCents: 1790,
    imageUrl: getMenuImageChoice("seafood").url,
    isAvailable: true,
    sortOrder: 4,
    options: [
      {
        id: "opt-salmon-sauce",
        menuItemId: "item-grilled-salmon",
        name: "Extra lemon butter",
        priceDeltaCents: 90,
      },
    ],
  },
  {
    id: "item-ribeye",
    restaurantId: "restaurant-demo",
    categoryId: "cat-mains",
    name: "Ribeye Steak",
    description: "Seared ribeye with roasted vegetables and pepper sauce.",
    priceCents: 2450,
    imageUrl: getMenuImageChoice("steak").url,
    isAvailable: true,
    sortOrder: 5,
    options: [
      {
        id: "opt-ribeye-fries",
        menuItemId: "item-ribeye",
        name: "Add fries",
        priceDeltaCents: 220,
      },
    ],
  },
  {
    id: "item-iced-tea",
    restaurantId: "restaurant-demo",
    categoryId: "cat-drinks",
    name: "House Lager",
    description: "Crisp draft lager served cold.",
    priceCents: 450,
    imageUrl: getMenuImageChoice("tea").url,
    isAvailable: true,
    sortOrder: 1,
    options: [
      {
        id: "opt-tea-less-sugar",
        menuItemId: "item-iced-tea",
        name: "Pint",
        priceDeltaCents: 0,
      },
    ],
  },
  {
    id: "item-cold-brew",
    restaurantId: "restaurant-demo",
    categoryId: "cat-drinks",
    name: "Cold Brew Coffee",
    description: "Slow-steeped coffee served over ice.",
    priceCents: 520,
    imageUrl: getMenuImageChoice("coffee").url,
    isAvailable: true,
    sortOrder: 2,
    options: [
      {
        id: "opt-cold-brew-oat",
        menuItemId: "item-cold-brew",
        name: "Oat milk",
        priceDeltaCents: 80,
      },
    ],
  },
  {
    id: "item-lime-soda",
    restaurantId: "restaurant-demo",
    categoryId: "cat-drinks",
    name: "Gin and Tonic",
    description: "House gin, tonic, lime, and ice.",
    priceCents: 790,
    imageUrl: getMenuImageChoice("tea").url,
    isAvailable: true,
    sortOrder: 3,
    options: [],
  },
  {
    id: "item-mango-sticky-rice",
    restaurantId: "restaurant-demo",
    categoryId: "cat-desserts",
    name: "Sticky Toffee Pudding",
    description: "Warm date sponge with toffee sauce and vanilla ice cream.",
    priceCents: 690,
    imageUrl: getMenuImageChoice("dessert").url,
    isAvailable: true,
    sortOrder: 1,
    options: [
      {
        id: "opt-mango-extra",
        menuItemId: "item-mango-sticky-rice",
        name: "Extra ice cream",
        priceDeltaCents: 180,
      },
    ],
  },
  {
    id: "item-coconut-cake",
    restaurantId: "restaurant-demo",
    categoryId: "cat-desserts",
    name: "Chocolate Brownie",
    description: "Warm brownie with chocolate sauce and whipped cream.",
    priceCents: 640,
    imageUrl: getMenuImageChoice("cake").url,
    isAvailable: true,
    sortOrder: 2,
    options: [],
  },
];

export const demoState: MenuMasterState = {
  restaurant: {
    id: "restaurant-demo",
    name: "MenuMaster Pub & Bar",
    slug: "menumaster-pub-bar",
    serviceRate: 0.1,
    taxRate: 0.07,
  },
  tables,
  categories: [
    {
      id: "cat-starters",
      restaurantId: "restaurant-demo",
      name: "Bar Bites",
      sortOrder: 1,
    },
    {
      id: "cat-mains",
      restaurantId: "restaurant-demo",
      name: "Pub Classics",
      sortOrder: 2,
    },
    {
      id: "cat-drinks",
      restaurantId: "restaurant-demo",
      name: "Drinks",
      sortOrder: 3,
    },
    {
      id: "cat-desserts",
      restaurantId: "restaurant-demo",
      name: "Desserts",
      sortOrder: 4,
    },
  ],
  menuItems,
  orders: [
    {
      id: "order-demo-1",
      restaurantId: "restaurant-demo",
      tableId: "table-12",
      tableName: "Table 12",
      status: "preparing",
      subtotalCents: 2180,
      serviceCents: 218,
      taxCents: 168,
      discountCents: 0,
      totalCents: 2566,
      createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
      items: [
        {
          id: "order-item-demo-1",
          orderId: "order-demo-1",
          menuItemId: "item-satay",
          name: "Buffalo Wings",
          quantity: 1,
          unitPriceCents: 890,
          lineTotalCents: 890,
          selectedOptions: [],
        },
        {
          id: "order-item-demo-2",
          orderId: "order-demo-1",
          menuItemId: "item-pad-thai",
          name: "House Burger",
          quantity: 1,
          unitPriceCents: 1290,
          lineTotalCents: 1290,
          selectedOptions: [],
        },
      ],
    },
  ],
  payments: [],
};
